package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aluguel generated by hbm2java
 */
public class Aluguel  implements java.io.Serializable {


     private Integer aluguelId;
     private Date dataDeAluguel;
     private int inventarioId;
     private short clienteId;
     private Date dataDeDevolucao;
     private byte funcionarioId;
     private Date ultimaAtualizacao;
     private Set pagamentos = new HashSet(0);

    public Aluguel() {
    }

	
    public Aluguel(Date dataDeAluguel, int inventarioId, short clienteId, byte funcionarioId, Date ultimaAtualizacao) {
        this.dataDeAluguel = dataDeAluguel;
        this.inventarioId = inventarioId;
        this.clienteId = clienteId;
        this.funcionarioId = funcionarioId;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Aluguel(Date dataDeAluguel, int inventarioId, short clienteId, Date dataDeDevolucao, byte funcionarioId, Date ultimaAtualizacao, Set pagamentos) {
       this.dataDeAluguel = dataDeAluguel;
       this.inventarioId = inventarioId;
       this.clienteId = clienteId;
       this.dataDeDevolucao = dataDeDevolucao;
       this.funcionarioId = funcionarioId;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.pagamentos = pagamentos;
    }
   
    public Integer getAluguelId() {
        return this.aluguelId;
    }
    
    public void setAluguelId(Integer aluguelId) {
        this.aluguelId = aluguelId;
    }
    public Date getDataDeAluguel() {
        return this.dataDeAluguel;
    }
    
    public void setDataDeAluguel(Date dataDeAluguel) {
        this.dataDeAluguel = dataDeAluguel;
    }
    public int getInventarioId() {
        return this.inventarioId;
    }
    
    public void setInventarioId(int inventarioId) {
        this.inventarioId = inventarioId;
    }
    public short getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(short clienteId) {
        this.clienteId = clienteId;
    }
    public Date getDataDeDevolucao() {
        return this.dataDeDevolucao;
    }
    
    public void setDataDeDevolucao(Date dataDeDevolucao) {
        this.dataDeDevolucao = dataDeDevolucao;
    }
    public byte getFuncionarioId() {
        return this.funcionarioId;
    }
    
    public void setFuncionarioId(byte funcionarioId) {
        this.funcionarioId = funcionarioId;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getPagamentos() {
        return this.pagamentos;
    }
    
    public void setPagamentos(Set pagamentos) {
        this.pagamentos = pagamentos;
    }




}


