package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ator generated by hbm2java
 */
public class Ator  implements java.io.Serializable {


     private Short atorId;
     private String primeiroNome;
     private String ultimoNome;
     private Date ultimaAtualizacao;
     private Set filmeAtors = new HashSet(0);

    public Ator() {
    }

	
    public Ator(String primeiroNome, String ultimoNome, Date ultimaAtualizacao) {
        this.primeiroNome = primeiroNome;
        this.ultimoNome = ultimoNome;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Ator(String primeiroNome, String ultimoNome, Date ultimaAtualizacao, Set filmeAtors) {
       this.primeiroNome = primeiroNome;
       this.ultimoNome = ultimoNome;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.filmeAtors = filmeAtors;
    }
   
    public Short getAtorId() {
        return this.atorId;
    }
    
    public void setAtorId(Short atorId) {
        this.atorId = atorId;
    }
    public String getPrimeiroNome() {
        return this.primeiroNome;
    }
    
    public void setPrimeiroNome(String primeiroNome) {
        this.primeiroNome = primeiroNome;
    }
    public String getUltimoNome() {
        return this.ultimoNome;
    }
    
    public void setUltimoNome(String ultimoNome) {
        this.ultimoNome = ultimoNome;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getFilmeAtors() {
        return this.filmeAtors;
    }
    
    public void setFilmeAtors(Set filmeAtors) {
        this.filmeAtors = filmeAtors;
    }




}


