package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Byte categoriaId;
     private String nome;
     private Date ultimaAtualizacao;
     private Set filmeCategorias = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nome, Date ultimaAtualizacao) {
        this.nome = nome;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Categoria(String nome, Date ultimaAtualizacao, Set filmeCategorias) {
       this.nome = nome;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.filmeCategorias = filmeCategorias;
    }
   
    public Byte getCategoriaId() {
        return this.categoriaId;
    }
    
    public void setCategoriaId(Byte categoriaId) {
        this.categoriaId = categoriaId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getFilmeCategorias() {
        return this.filmeCategorias;
    }
    
    public void setFilmeCategorias(Set filmeCategorias) {
        this.filmeCategorias = filmeCategorias;
    }




}


