package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Short clienteId;
     private byte lojaId;
     private String primeiroNome;
     private String ultimoNome;
     private String genero;
     private String escolaridade;
     private BigDecimal renda;
     private String email;
     private short enderecoId;
     private boolean ativo;
     private Date dataCriacao;
     private Date ultimaAtualizacao;
     private Set pagamentos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(byte lojaId, String primeiroNome, String ultimoNome, String genero, short enderecoId, boolean ativo, Date dataCriacao, Date ultimaAtualizacao) {
        this.lojaId = lojaId;
        this.primeiroNome = primeiroNome;
        this.ultimoNome = ultimoNome;
        this.genero = genero;
        this.enderecoId = enderecoId;
        this.ativo = ativo;
        this.dataCriacao = dataCriacao;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Cliente(byte lojaId, String primeiroNome, String ultimoNome, String genero, String escolaridade, BigDecimal renda, String email, short enderecoId, boolean ativo, Date dataCriacao, Date ultimaAtualizacao, Set pagamentos) {
       this.lojaId = lojaId;
       this.primeiroNome = primeiroNome;
       this.ultimoNome = ultimoNome;
       this.genero = genero;
       this.escolaridade = escolaridade;
       this.renda = renda;
       this.email = email;
       this.enderecoId = enderecoId;
       this.ativo = ativo;
       this.dataCriacao = dataCriacao;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.pagamentos = pagamentos;
    }
   
    public Short getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Short clienteId) {
        this.clienteId = clienteId;
    }
    public byte getLojaId() {
        return this.lojaId;
    }
    
    public void setLojaId(byte lojaId) {
        this.lojaId = lojaId;
    }
    public String getPrimeiroNome() {
        return this.primeiroNome;
    }
    
    public void setPrimeiroNome(String primeiroNome) {
        this.primeiroNome = primeiroNome;
    }
    public String getUltimoNome() {
        return this.ultimoNome;
    }
    
    public void setUltimoNome(String ultimoNome) {
        this.ultimoNome = ultimoNome;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getEscolaridade() {
        return this.escolaridade;
    }
    
    public void setEscolaridade(String escolaridade) {
        this.escolaridade = escolaridade;
    }
    public BigDecimal getRenda() {
        return this.renda;
    }
    
    public void setRenda(BigDecimal renda) {
        this.renda = renda;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public short getEnderecoId() {
        return this.enderecoId;
    }
    
    public void setEnderecoId(short enderecoId) {
        this.enderecoId = enderecoId;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Date getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getPagamentos() {
        return this.pagamentos;
    }
    
    public void setPagamentos(Set pagamentos) {
        this.pagamentos = pagamentos;
    }




}


