package model;
// Generated 29/08/2017 01:55:11 by Hibernate Tools 4.3.1



/**
 * DwalugueisFato generated by hbm2java
 */
public class DwalugueisFato  implements java.io.Serializable {


     private int idAlugueis;
     private Dwcliente dwcliente;
     private DwfilmeCategoria dwfilmeCategoria;
     private Dwloja dwloja;
     private Dwtempo dwtempo;
     private Integer quantidade;
     private Float valor;

    public DwalugueisFato() {
    }

	
    public DwalugueisFato(int idAlugueis, Dwcliente dwcliente, DwfilmeCategoria dwfilmeCategoria, Dwloja dwloja, Dwtempo dwtempo) {
        this.idAlugueis = idAlugueis;
        this.dwcliente = dwcliente;
        this.dwfilmeCategoria = dwfilmeCategoria;
        this.dwloja = dwloja;
        this.dwtempo = dwtempo;
    }
    public DwalugueisFato(int idAlugueis, Dwcliente dwcliente, DwfilmeCategoria dwfilmeCategoria, Dwloja dwloja, Dwtempo dwtempo, Integer quantidade, Float valor) {
       this.idAlugueis = idAlugueis;
       this.dwcliente = dwcliente;
       this.dwfilmeCategoria = dwfilmeCategoria;
       this.dwloja = dwloja;
       this.dwtempo = dwtempo;
       this.quantidade = quantidade;
       this.valor = valor;
    }
   
    public int getIdAlugueis() {
        return this.idAlugueis;
    }
    
    public void setIdAlugueis(int idAlugueis) {
        this.idAlugueis = idAlugueis;
    }
    public Dwcliente getDwcliente() {
        return this.dwcliente;
    }
    
    public void setDwcliente(Dwcliente dwcliente) {
        this.dwcliente = dwcliente;
    }
    public DwfilmeCategoria getDwfilmeCategoria() {
        return this.dwfilmeCategoria;
    }
    
    public void setDwfilmeCategoria(DwfilmeCategoria dwfilmeCategoria) {
        this.dwfilmeCategoria = dwfilmeCategoria;
    }
    public Dwloja getDwloja() {
        return this.dwloja;
    }
    
    public void setDwloja(Dwloja dwloja) {
        this.dwloja = dwloja;
    }
    public Dwtempo getDwtempo() {
        return this.dwtempo;
    }
    
    public void setDwtempo(Dwtempo dwtempo) {
        this.dwtempo = dwtempo;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }




}


