package model;
// Generated 29/08/2017 01:55:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DwfilmeCategoria generated by hbm2java
 */
public class DwfilmeCategoria  implements java.io.Serializable {


     private int idFilmeCategoria;
     private String categoria;
     private Set dwalugueisFatos = new HashSet(0);

    public DwfilmeCategoria() {
    }

	
    public DwfilmeCategoria(int idFilmeCategoria) {
        this.idFilmeCategoria = idFilmeCategoria;
    }
    public DwfilmeCategoria(int idFilmeCategoria, String categoria, Set dwalugueisFatos) {
       this.idFilmeCategoria = idFilmeCategoria;
       this.categoria = categoria;
       this.dwalugueisFatos = dwalugueisFatos;
    }
   
    public int getIdFilmeCategoria() {
        return this.idFilmeCategoria;
    }
    
    public void setIdFilmeCategoria(int idFilmeCategoria) {
        this.idFilmeCategoria = idFilmeCategoria;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set getDwalugueisFatos() {
        return this.dwalugueisFatos;
    }
    
    public void setDwalugueisFatos(Set dwalugueisFatos) {
        this.dwalugueisFatos = dwalugueisFatos;
    }




}


