package model;
// Generated 29/08/2017 01:55:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dwloja generated by hbm2java
 */
public class Dwloja  implements java.io.Serializable {


     private int idLoja;
     private String cidade;
     private String estado;
     private Set dwalugueisFatos = new HashSet(0);

    public Dwloja() {
    }

	
    public Dwloja(int idLoja) {
        this.idLoja = idLoja;
    }
    public Dwloja(int idLoja, String cidade, String estado, Set dwalugueisFatos) {
       this.idLoja = idLoja;
       this.cidade = cidade;
       this.estado = estado;
       this.dwalugueisFatos = dwalugueisFatos;
    }
   
    public int getIdLoja() {
        return this.idLoja;
    }
    
    public void setIdLoja(int idLoja) {
        this.idLoja = idLoja;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDwalugueisFatos() {
        return this.dwalugueisFatos;
    }
    
    public void setDwalugueisFatos(Set dwalugueisFatos) {
        this.dwalugueisFatos = dwalugueisFatos;
    }




}


