package model;
// Generated 29/08/2017 01:55:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dwtempo generated by hbm2java
 */
public class Dwtempo  implements java.io.Serializable {


     private Integer idTempo;
     private String diaSemana;
     private String mes;
     private String quadrimestre;
     private Set dwalugueisFatos = new HashSet(0);

    public Dwtempo() {
    }

    public Dwtempo(String diaSemana, String mes, String quadrimestre, Set dwalugueisFatos) {
       this.diaSemana = diaSemana;
       this.mes = mes;
       this.quadrimestre = quadrimestre;
       this.dwalugueisFatos = dwalugueisFatos;
    }
   
    public Integer getIdTempo() {
        return this.idTempo;
    }
    
    public void setIdTempo(Integer idTempo) {
        this.idTempo = idTempo;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public String getQuadrimestre() {
        return this.quadrimestre;
    }
    
    public void setQuadrimestre(String quadrimestre) {
        this.quadrimestre = quadrimestre;
    }
    public Set getDwalugueisFatos() {
        return this.dwalugueisFatos;
    }
    
    public void setDwalugueisFatos(Set dwalugueisFatos) {
        this.dwalugueisFatos = dwalugueisFatos;
    }




}


