package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private Integer id;
     private String uf;
     private String nome;
     private Set cidades = new HashSet(0);

    public Estados() {
    }

	
    public Estados(String uf, String nome) {
        this.uf = uf;
        this.nome = nome;
    }
    public Estados(String uf, String nome, Set cidades) {
       this.uf = uf;
       this.nome = nome;
       this.cidades = cidades;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


