package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FilmeAtor generated by hbm2java
 */
public class FilmeAtor  implements java.io.Serializable {


     private FilmeAtorId id;
     private Ator ator;
     private Filme filme;
     private Date ultimaAtualizacao;

    public FilmeAtor() {
    }

    public FilmeAtor(FilmeAtorId id, Ator ator, Filme filme, Date ultimaAtualizacao) {
       this.id = id;
       this.ator = ator;
       this.filme = filme;
       this.ultimaAtualizacao = ultimaAtualizacao;
    }
   
    public FilmeAtorId getId() {
        return this.id;
    }
    
    public void setId(FilmeAtorId id) {
        this.id = id;
    }
    public Ator getAtor() {
        return this.ator;
    }
    
    public void setAtor(Ator ator) {
        this.ator = ator;
    }
    public Filme getFilme() {
        return this.filme;
    }
    
    public void setFilme(Filme filme) {
        this.filme = filme;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }




}


