package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1



/**
 * FilmeTexto generated by hbm2java
 */
public class FilmeTexto  implements java.io.Serializable {


     private short filmeId;
     private String titulo;
     private String descricao;

    public FilmeTexto() {
    }

	
    public FilmeTexto(short filmeId, String titulo) {
        this.filmeId = filmeId;
        this.titulo = titulo;
    }
    public FilmeTexto(short filmeId, String titulo, String descricao) {
       this.filmeId = filmeId;
       this.titulo = titulo;
       this.descricao = descricao;
    }
   
    public short getFilmeId() {
        return this.filmeId;
    }
    
    public void setFilmeId(short filmeId) {
        this.filmeId = filmeId;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


