package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1



/**
 * FilmeCategoriaId generated by hbm2java
 */
public class FilmeCategoriaId  implements java.io.Serializable {


     private short filmeId;
     private byte categoriaId;

    public FilmeCategoriaId() {
    }

    public FilmeCategoriaId(short filmeId, byte categoriaId) {
       this.filmeId = filmeId;
       this.categoriaId = categoriaId;
    }
   
    public short getFilmeId() {
        return this.filmeId;
    }
    
    public void setFilmeId(short filmeId) {
        this.filmeId = filmeId;
    }
    public byte getCategoriaId() {
        return this.categoriaId;
    }
    
    public void setCategoriaId(byte categoriaId) {
        this.categoriaId = categoriaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FilmeCategoriaId) ) return false;
		 FilmeCategoriaId castOther = ( FilmeCategoriaId ) other; 
         
		 return (this.getFilmeId()==castOther.getFilmeId())
 && (this.getCategoriaId()==castOther.getCategoriaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFilmeId();
         result = 37 * result + this.getCategoriaId();
         return result;
   }   


}


