package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FilmeCategoria generated by hbm2java
 */
public class FilmeCategoria  implements java.io.Serializable {


     private FilmeCategoriaId id;
     private Categoria categoria;
     private Filme filme;
     private Date ultimaAtualizacao;

    public FilmeCategoria() {
    }

    public FilmeCategoria(FilmeCategoriaId id, Categoria categoria, Filme filme, Date ultimaAtualizacao) {
       this.id = id;
       this.categoria = categoria;
       this.filme = filme;
       this.ultimaAtualizacao = ultimaAtualizacao;
    }
   
    public FilmeCategoriaId getId() {
        return this.id;
    }
    
    public void setId(FilmeCategoriaId id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Filme getFilme() {
        return this.filme;
    }
    
    public void setFilme(Filme filme) {
        this.filme = filme;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }




}


