package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1



/**
 * FilmeAtorId generated by hbm2java
 */
public class FilmeAtorId  implements java.io.Serializable {


     private short atorId;
     private short filmeId;

    public FilmeAtorId() {
    }

    public FilmeAtorId(short atorId, short filmeId) {
       this.atorId = atorId;
       this.filmeId = filmeId;
    }
   
    public short getAtorId() {
        return this.atorId;
    }
    
    public void setAtorId(short atorId) {
        this.atorId = atorId;
    }
    public short getFilmeId() {
        return this.filmeId;
    }
    
    public void setFilmeId(short filmeId) {
        this.filmeId = filmeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FilmeAtorId) ) return false;
		 FilmeAtorId castOther = ( FilmeAtorId ) other; 
         
		 return (this.getAtorId()==castOther.getAtorId())
 && (this.getFilmeId()==castOther.getFilmeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAtorId();
         result = 37 * result + this.getFilmeId();
         return result;
   }   


}


