package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Idioma generated by hbm2java
 */
public class Idioma  implements java.io.Serializable {


     private Byte idiomaId;
     private String nome;
     private Date ultimaAtualizacao;

    public Idioma() {
    }

    public Idioma(String nome, Date ultimaAtualizacao) {
       this.nome = nome;
       this.ultimaAtualizacao = ultimaAtualizacao;
    }
   
    public Byte getIdiomaId() {
        return this.idiomaId;
    }
    
    public void setIdiomaId(Byte idiomaId) {
        this.idiomaId = idiomaId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }




}


