package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer inventarioId;
     private Filme filme;
     private Loja loja;
     private Date ultimaAtualizacao;

    public Inventario() {
    }

    public Inventario(Filme filme, Loja loja, Date ultimaAtualizacao) {
       this.filme = filme;
       this.loja = loja;
       this.ultimaAtualizacao = ultimaAtualizacao;
    }
   
    public Integer getInventarioId() {
        return this.inventarioId;
    }
    
    public void setInventarioId(Integer inventarioId) {
        this.inventarioId = inventarioId;
    }
    public Filme getFilme() {
        return this.filme;
    }
    
    public void setFilme(Filme filme) {
        this.filme = filme;
    }
    public Loja getLoja() {
        return this.loja;
    }
    
    public void setLoja(Loja loja) {
        this.loja = loja;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }




}


