package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Loja generated by hbm2java
 */
public class Loja  implements java.io.Serializable {


     private Byte lojaId;
     private byte gerenteId;
     private short enderecoId;
     private Date ultimaAtualizacao;
     private Set inventarios = new HashSet(0);
     private Set funcionarios = new HashSet(0);

    public Loja() {
    }

	
    public Loja(byte gerenteId, short enderecoId, Date ultimaAtualizacao) {
        this.gerenteId = gerenteId;
        this.enderecoId = enderecoId;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Loja(byte gerenteId, short enderecoId, Date ultimaAtualizacao, Set inventarios, Set funcionarios) {
       this.gerenteId = gerenteId;
       this.enderecoId = enderecoId;
       this.ultimaAtualizacao = ultimaAtualizacao;
       this.inventarios = inventarios;
       this.funcionarios = funcionarios;
    }
   
    public Byte getLojaId() {
        return this.lojaId;
    }
    
    public void setLojaId(Byte lojaId) {
        this.lojaId = lojaId;
    }
    public byte getGerenteId() {
        return this.gerenteId;
    }
    
    public void setGerenteId(byte gerenteId) {
        this.gerenteId = gerenteId;
    }
    public short getEnderecoId() {
        return this.enderecoId;
    }
    
    public void setEnderecoId(short enderecoId) {
        this.enderecoId = enderecoId;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


