package model;
// Generated 28/08/2017 09:48:42 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento  implements java.io.Serializable {


     private Short pagamentoId;
     private Aluguel aluguel;
     private Cliente cliente;
     private Funcionario funcionario;
     private BigDecimal valor;
     private Date dataDePagamento;
     private Date ultimaAtualizacao;

    public Pagamento() {
    }

	
    public Pagamento(Cliente cliente, Funcionario funcionario, BigDecimal valor, Date dataDePagamento, Date ultimaAtualizacao) {
        this.cliente = cliente;
        this.funcionario = funcionario;
        this.valor = valor;
        this.dataDePagamento = dataDePagamento;
        this.ultimaAtualizacao = ultimaAtualizacao;
    }
    public Pagamento(Aluguel aluguel, Cliente cliente, Funcionario funcionario, BigDecimal valor, Date dataDePagamento, Date ultimaAtualizacao) {
       this.aluguel = aluguel;
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.valor = valor;
       this.dataDePagamento = dataDePagamento;
       this.ultimaAtualizacao = ultimaAtualizacao;
    }
   
    public Short getPagamentoId() {
        return this.pagamentoId;
    }
    
    public void setPagamentoId(Short pagamentoId) {
        this.pagamentoId = pagamentoId;
    }
    public Aluguel getAluguel() {
        return this.aluguel;
    }
    
    public void setAluguel(Aluguel aluguel) {
        this.aluguel = aluguel;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Date getDataDePagamento() {
        return this.dataDePagamento;
    }
    
    public void setDataDePagamento(Date dataDePagamento) {
        this.dataDePagamento = dataDePagamento;
    }
    public Date getUltimaAtualizacao() {
        return this.ultimaAtualizacao;
    }
    
    public void setUltimaAtualizacao(Date ultimaAtualizacao) {
        this.ultimaAtualizacao = ultimaAtualizacao;
    }




}


